idf_component_register(
  SRCS
    "src/alc_esp32_timer.cc"
    "src/alc_storage.cc"
    "src/alc_utils.cc"
    "src/alc_wifi_controller.cc"
    "src/alc_i2c_bus_manager.cc"
    "src/alc_bme280_sensor.cc"
    "src/alc_bno086_sensor.cc"
    "src/alc_max_m10s_sensor.cc"
  PRIV_INCLUDE_DIRS
    "src"
  INCLUDE_DIRS
    "include"
  REQUIRES
    "esp_timer"
    "esp_common"
    "esp_wifi"
    "nvs_flash"
    "cjson"
    "driver"
  PRIV_REQUIRES
    "log"
    "esp_http_client"
)
